### ISSUE TITLE
EDITOR, anteprima pubblicità

### ISSUE THREAD

**Issue by murdercode** [The-3Labs-Team/tinymce-laravel-shortcode-plus#34]
Toggle di attivazione

**Comment by murdercode** [comment]
```
TypeError: Cannot read properties of undefined (reading 'before')
    at insertAdv (previewAdv.js:89:41)
    at YO.<anonymous> (previewAdv.js:42:5)
    at EO.dispatch (tinymce.min.js:4:394131)
    at YO.dispatch (tinymce.min.js:4:395385)
    at tinymce.min.js:4:367697
    at tinymce.min.js:4:367715
    at BT (tinymce.min.js:4:368129)
    at tinymce.min.js:4:376451
```

Missing config for before/after

**Comment by murdercode** [comment]
È ancora in conflitto con le config

**Comment by murdercode** [comment]
Si ferma al primo adv da mostrare

**Comment by Claudio-Emmolo** [comment]
Cambio Icona
